openapi: 3.0.1
info:
  title: My API
  version: v1
paths:
  '/course/{id}':
    get:
      tags:
        - Course
      parameters:
        - name: id
          in: path
          required: true
          style: simple
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Course'
            application/json:
              schema:
                $ref: '#/components/schemas/Course'
            text/json:
              schema:
                $ref: '#/components/schemas/Course'
    put:
      tags:
        - Course
      parameters:
        - name: id
          in: path
          required: true
          style: simple
          schema:
            type: string
        - name: mentorId
          in: query
          style: form
          schema:
            type: string
        - name: price
          in: query
          style: form
          schema:
            type: number
            format: double
        - name: ratingStar
          in: query
          style: form
          schema:
            type: number
            format: double
      responses:
        '200':
          description: Success
    delete:
      tags:
        - Course
      parameters:
        - name: id
          in: path
          required: true
          style: simple
          schema:
            type: string
      responses:
        '200':
          description: Success
  /course:
    get:
      tags:
        - Course
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Course'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Course'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Course'
    post:
      tags:
        - Course
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Course'
          text/json:
            schema:
              $ref: '#/components/schemas/Course'
          application/*+json:
            schema:
              $ref: '#/components/schemas/Course'
      responses:
        '200':
          description: Success
  /api/Message:
    post:
      tags:
        - Message
      responses:
        '200':
          description: Success
  /user/register:
    post:
      tags:
        - User
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
          text/json:
            schema:
              $ref: '#/components/schemas/User'
          application/*+json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: Success
  /user/login:
    post:
      tags:
        - User
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
          text/json:
            schema:
              $ref: '#/components/schemas/User'
          application/*+json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: Success
components:
  schemas:
    Course:
      type: object
      properties:
        id:
          type: string
          nullable: true
        mentorId:
          type: string
          nullable: true
        price:
          type: number
          format: double
        ratingStar:
          type: number
          format: double
        createdAt:
          type: string
          format: date-time
      additionalProperties: false
    User:
      type: object
      properties:
        id:
          type: string
          nullable: true
        displayName:
          type: string
          nullable: true
        password:
          type: string
          nullable: true
        email:
          type: string
          nullable: true
        phoneNumber:
          type: string
          nullable: true
      additionalProperties: false