name : Deploy Swagger Page
on:
  push:
    branches:
      - main
      - gh-pages
jobs:
  generate-openapi-spec:
    runs-on: windows-latest
    steps: 
      - uses: actions/checkout@v4.1.0
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3.2.0
        with:
          dotnet-version: 7.*.*
      - name: Install dependencies
        run: dotnet restore
      - name: Publish
        run: dotnet publish --configuration Release --no-restore
      - name: Install tools
        working-directory: ./
        run: dotnet tool restore
      - name: Generate openapi.json
        working-directory: ./
        run: swagger tofile --output ".\openapi.json" ".\bin\Release\net7.0\publish\MentorShip.dll" "v1"
      - name: Upload openapi.json
        uses: actions/upload-artifact@v3.1.3
        with:
          name: api-spec-file
          path: openapi.json
      
        
  deploy:
    needs: generate-openapi-spec
    runs-on: ubuntu-latest
    steps:
      - name: Download openapi.json
        uses: actions/download-artifact@v2.1.1
        with:
          name: api-spec-file
      - name: Generate Swagger UI
        uses: Legion2/swagger-ui-action@v1.1.6
        with:
          output: swagger-ui
          spec-file: openapi.json
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-github-pages@v3.1.12
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: swagger-ui